/*
 * param_config.h
 *
 *  Created on: 2024年3月8日
 *      Author: Dell
 */

#ifndef COMMON_MID_INC_PARAM_CONFIG_H_
#define COMMON_MID_INC_PARAM_CONFIG_H_

#include "bsp_flash.h"
#include "flash_alloca.h"



#define FLASH_PARAM_MAX_NUM    		126
#define SN_NUM 						16
typedef struct
{
	uint16_t def;
	uint16_t defmin;
	uint16_t defmax;
}param_str;

typedef enum
{
	Param_Index_Start = 0,
	RS485_BD = Param_Index_Start,
	RS485_ADD,
	SELF_CIR_START_DEV,
	SELF_CIR_STOP_DEV,
	OUT_WATER_CTL_REF_TEMP,
	OUT_WATER_CTL_HEAT_TEMP,
	IN_WATER_CTL_REF_TEMP,
	IN_WATER_CTL_HEAT_TEMP,
	BMS_TEMP_CTL_REF_TEMP,
	BMS_TEMP_CTL_HEAT_TEMP,
	REF_BACKLASH,
	HEAT_BACKLASH,
	PUMP_HIGH_DUTY,
	PUMP_MIDDLE_DUTY,
	PUMP_LOW_DUTY,
	FAN_HIGH_DUTY,
	FAN_MIDDLE_DUTY,
	FAN_LOW_DUTY,
	FAN_INC_TEMP,
	FAN_DEC_TEMP,
	HIGH_PRES_PROTECT_TEMP,
	LOW_PRES_PROTECT_TEMP,
	OUT_MOTOR_HIGH_TEMP_PROTECT,
	IN_WATER_LOW_PRES_PROTECT,
	OUT_WATER_HIGH_PRES_PROTECT,
	EXPAN_INIT_OPEN_1,
	EXPAN_INIT_OPEN_2,
	EXPAN_INIT_OPEN_3,
	EXPAN_INIT_OPEN_4,
	EXPAN_INIT_OPEN_5,
	OVER_HEAT_POINT1,
	OVER_HEAT_POINT2,
	OVER_HEAT_POINT3,
	OVER_HEAT_POINT4,
	OVER_HEAT_POINT5,
	EXPAN_MIN_OPEN,
	EXPAN_CTL_INTERVAL,
	EXPAN_INIT_HOLD_TIME,
	UNIT_INTERVAL,
	MOTOR_START_INTERVAL,
	REF_MIN_TEMP,
	REF_MAX_TEMP,
	MOTOR_FRE_LIMIT1,
	MOTOR_FRE_LIMIT2,
	MOTOR_FRE_LIMIT3,
	MOTOR_FRE_LIMIT4,
	MOTOR_FRE_LIMIT5,
	MOTOR_FRE_LIMIT6,
	MOTOR_FRE_MAX,
	MOTOR_FRE_MIN,
	TEST_HOLD_TIME,
	CTL_TEMP_SET,
	OUT_WATER_TEMP_HIGH,
	OUT_WATER_TEMP_LOW,
	START_MODE,
	UNIT_SELECT,
	VALVE_START_TEMP,
	SN1,
	SN2,
	SN3,
	SN4,
	SN5,
	SN6,
	SN7,
	SN8,
	SN9,
	SN10,
	SN11,
	SN12,
	SN13,
	SN14,
	SN15,
	SN16,
	POWER_CONTROL_BOARD_ERR_NUM,
	POWER_EXPAN_ERR_NUM,
	ADCREF_CONTROL_BOARD_ERR_NUM,
	COMMUNICATION_MOTOR_ERR_NUM,
	COMMUNICATION_HOST_ERR_NUM,
	IN_WATAR_TEMP_SENSOR_ERR_NUM,
	OUT_WATER_TEMP_SENSOR_ERR_NUM,
	IN_MOTOR_TEMP_SENSOR_ERR_NUM,
	OUT_MOTOR_TEMP_SENSOR_ERR_NUM,
	ENVIRONMENT_TEMP_SENSOR_ERR_NUM,
	IN_WATER_PRES_SENSOR_ERR_NUM,
	OUT_WATER_PRES_SENSOR_ERR_NUM,
	IN_MOTOR_PRES_SENSOR_ERR_NUM,
	OUT_MOTOR_PRES_SENSOR_ERR_NUM,
	IN_MOTOR_PRES_LOW_ERR_NUM,
	OUT_MOTOR_PRES_HIGH_ERR_NUM,
	OUT_MOTOR_TEMP_HIGH_ERR_NUM,
	FAN1_ERR_NUM,
	FAN2_ERR_NUM,
	FAN3_ERR_NUM,
	COMPRE_FRE_ERR_NUM,
	OUT_WATER_PRES_LOW_ERR_NUM,
	OUT_WATER_PRES_HIGH_ERR_NUM,
	OUT_WATER_TEMP_LOW_ERR_NUM,
	OUT_WATER_TEMP_HIGH_ERR_NUM,
	PUMP_ERR_NUM,
	PTC_ERR_NUM,
	TEMP_OVER_ERR_NUM,
	PTC_RUN_TIME,
	MOTOR_RUN_TIME,
	PTC_RUN_CNT,
	MOTOR_RUN_CNT,
	PTC_RUN_TIME_TEMP,
	MOTOR_RUN_TIME_TEMP,
	Param_Index_End,
}PARA_LIST_E;

void Param_Download(void);
void Param_Init(void);
uint8_t Param_Set(uint8_t Index,uint16_t data);
uint16_t Param_Get(uint8_t Index);
void Param_Download(void);
void Param_Reset(void);
#endif /* COMMON_MID_INC_PARAM_CONFIG_H_ */
